# Generated by Django 3.2.25 on 2025-03-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=5000)),
                ('banner_image', models.FileField(upload_to='images')),
                ('resource_link', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=60)),
                ('article', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LikeOrDisLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=60)),
                ('article', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('status', models.CharField(default='yes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=60)),
            ],
        ),
    ]
